### ISSUE TITLE
Drop support of Django<1.8

### ISSUE THREAD

**Issue by benoitbryon** [novafloss/django-anysign#21]
What about following Django's supported versions? See https://www.djangoproject.com/download/
Django supports 1.7, 1.8 and 1.4 branches. 1.4 is not supported by django-anysign, so only 1.7 and 1.8 remain.
=> Drop support for django 1.5 and django 1.6 in the next release.

It should make it easier to maintain the application and demo project.
Those who want support of legacy Django version will still be able to install legacy versions of django-anysign (versions are not deleted on PyPI).

**Comment by zebuline** [comment]
drop also support of django 1.7
